language: python
python:
- '3.6'

services: docker

git:
  depth: false

install: make docker-login build-docker

stages:
- name: publish-docker

jobs:
  include:
  - stage: publish
    name: Publish docker image
    script:
    - make docker-login publish-docker
